const $=x=>document.getElementById(x),get=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d)),set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));let profile=get('profile',{h:172,w:68,goal:1800,protect:true}),logs=get('logs',[]),est=0,today=()=>new Date().toISOString().slice(0,10);
function bmiCalc(){let b=profile.w/((profile.h/100)**2);$('bmi').textContent=b.toFixed(1);$('status').textContent=b<18.5?'體重過輕':b<24?'健康體位':b<27?'體重過重':'肥胖'}
function load(){$('h').value=profile.h;$('w').value=profile.w;$('goal').value=profile.goal;$('protect').checked=profile.protect;bmiCalc();renderPlans();renderLogs()}
$('save').onclick=()=>{profile={h:+$('h').value,w:+$('w').value,goal:+$('goal').value,protect:$('protect').checked};set('profile',profile);bmiCalc();renderLogs();alert('已儲存，下次不需重新輸入。')};$('protect').onchange=()=>{profile.protect=$('protect').checked;set('profile',profile);renderPlans()};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.p).classList.add('active')});
const ex=[['慢走（時速4公里）','低強度・輕鬆體驗','每日30分鐘，共1回','119','餐後幫助腸胃蠕動、控制血糖起伏、燃燒脂肪。',['選擇平坦安全路面。','可分3次，每次10分鐘。','不追求速度。'],'左腳疲勞、拖步加重或腫脹增加即停止。'],['快走／健走（時速6公里）','中強度・心肺訓練','每次15分鐘，共2回','220','提升心肺耐力與活動量。',['僅在慢走無不適後嘗試。','保持可說完整句子的強度。'],'目前仍在復健，應先取得物理治療師同意。'],['側身卷腹','低衝擊・核心訓練','每側8～10次，共2組','45','雕塑腹斜肌群，強化核心穩定。',['膝蓋只彎到可接受角度。','雙手輕扶頭部，不拉扯頸部。','受傷腿不要推地。'],'腰部、膝蓋或小腿不適即停止。'],['坐姿上肢訓練','低衝擊・上肢肌力','10～12分鐘','70','坐姿訓練肩膀、手臂與背部。',['坐穩有靠背椅子。','先徒手，再考慮極輕水瓶。'],'避免憋氣與前傾失衡。']];
function renderPlans(){$('plans').innerHTML='';ex.forEach((e,i)=>{if(profile.protect&&i===1)return;let d=document.createElement('div');d.className='exercise';d.innerHTML=`<div class="head"><div class="media">${i===2?'<img src="assets/side-crunch.gif">':`<span style="font-size:48px">${i===0?'🚶':i===1?'🏃':'🪑'}</span>`}</div><div><span class="tag">${e[1]}</span><h3>${e[0]}</h3><div class="dose">${e[2]}</div><p class="muted">${e[4]}</p></div></div><div class="details"><b>訓練規格與動作要領</b><ol>${e[5].map(x=>`<li>${x}</li>`).join('')}</ol><p>預估消耗：約 ${e[3]} kcal</p><p class="warm">溫馨提醒：${e[6]}</p></div><button>展開詳細動態解說 ›</button>`;d.querySelector('button').onclick=()=>d.classList.toggle('open');$('plans').appendChild(d)})}
function addComp(){let d=document.createElement('div');d.className='component';d.innerHTML='<input placeholder="內容物"><input type="number" value="30"><select><option>公克</option><option>片</option><option>顆</option><option>份</option></select><button>×</button>';d.querySelector('button').onclick=()=>d.remove();$('components').appendChild(d)}$('add').onclick=addComp;addComp();
const foods={'牛肉麵':720,'排骨便當':700,'便當':650,'鍋貼':75,'茶葉蛋':78,'蚵仔麵線':415,'鍋燒意麵':550,'宮保雞丁麵':423,'地瓜':125,'白飯':280};
function compK(n,a,u){let m={'滷排骨':260,'排骨':260,'番茄炒蛋':150,'蕃茄炒蛋':150,'地瓜葉':90,'豆干':155,'豆乾':155,'白飯':140,'雞胸':165,'雞腿':220,'豆腐':85,'牛肉':250,'豬肉':260,'魚':150},p=130;Object.keys(m).some(k=>n.includes(k)?(p=m[k],1):0);let g=u==='公克'?a:u==='片'?a*80:u==='顆'?a*50:a*100;return p*g/100}
$('estimate').onclick=()=>{let n=$('foodName').value,total=0;Object.keys(foods).some(k=>n.includes(k)?(total=foods[k]*+$('size').value*(+$('qty').value||1),1):0);document.querySelectorAll('.component').forEach(r=>{let i=r.children[0].value,a=+r.children[1].value,u=r.children[2].value;if(i&&a)total+=compK(i,a,u)});if(!total)total=500;est=Math.round(total);$('result').textContent='估算熱量：約 '+est+' kcal'};
$('saveFood').onclick=()=>{if(!est)return alert('請先概算熱量');logs.push({date:today(),name:$('foodName').value||'自訂餐點',kcal:est});set('logs',logs);renderLogs();alert('已加入今日紀錄')};$('clear').onclick=()=>{logs=logs.filter(x=>x.date!==today());set('logs',logs);renderLogs()};
function renderLogs(){let t=logs.filter(x=>x.date===today()),sum=t.reduce((a,b)=>a+b.kcal,0);$('logs').innerHTML=t.length?t.map(x=>`<div class="log"><span>${x.name}</span><b>${x.kcal} kcal</b></div>`).join(''):'尚未加入今日餐點。';$('used').textContent=sum;$('left').textContent=Math.max(0,profile.goal-sum)}
let prompt;$('install').hidden=true;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();prompt=e;$('install').hidden=false});$('install').onclick=async()=>{if(prompt){prompt.prompt();await prompt.userChoice;prompt=null}else alert('請使用 Chrome 選單的「安裝應用程式」或「加到主畫面」。')};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');load();